stages:
- name: Build--NPM build dist
  steps:
  - runScriptConfig:
      image: node:14
      shellScript: cd app; npm install; npm run build; ls
- name: Code Review--run Checkmarx test
  steps:
  - runScriptConfig:
      image: 10.20.0.73:5443/dockerhub/iiiorg/checkmarx-runner:latest
      shellScript: ln -s "$(pwd)" /usr/src/app/repo; cd /usr/src/app; ls; echo ${api_orign};node app.js;
    env:
      git_url: ${CICD_GIT_URL}
      git_branch: ${CICD_GIT_BRANCH}
      git_commit_id: ${CICD_GIT_COMMIT}
      verbose: true
    envFrom:
    - sourceName: nexus
      sourceKey: api-origin
      targetKey: api_origin
    - sourceName: nexus
      sourceKey: username
      targetKey: api_username
    - sourceName: nexus
      sourceKey: password
      targetKey: api_password
    - sourceName: checkmarx
      sourceKey: username
      targetKey: username
    - sourceName: checkmarx
      sourceKey: password
      targetKey: password
    - sourceName: checkmarx
      sourceKey: check-interval
      targetKey: check_interval
    - sourceName: checkmarx
      sourceKey: client-secret
      targetKey: client_secret
    - sourceName: checkmarx
      sourceKey: cm-url
      targetKey: cm_url
- name: Run webinspect-runner
  steps:
    - runScriptConfig:
        image: iiiorg/webinspect-runner
        shellScript: cd /usr/src/app; node /usr/src/app/app.js
      env:
        inspect_url: http://<Your k8s external host>:30185/
        project_name: ${CICD_GIT_REPO_NAME}
        git_branch: ${CICD_GIT_BRANCH}
        git_commit_id: ${CICD_GIT_COMMIT}
        verbose: true
      envFrom:
        - sourceName: webinspect
          sourceKey: wi-base-url
          targetKey: wi_base_url
        - sourceName: nexus
          sourceKey: username
          targetKey: api_username
        - sourceName: nexus
          sourceKey: password
          targetKey: api_password
        - sourceName: nexus
          sourceKey: api-origin
          targetKey: api_origin
- name: Publish--vuejs image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
- name: deploy--vuejs deployment and service on kubernetes
  steps:
  - applyYamlConfig:
      path: ./k8s-yaml/vuejs-deployment.yaml
  - applyYamlConfig:
      path: ./k8s-yaml/vuejs-service.yaml